setup_symlinks

diff --git a/Dockerfile.apps b/Dockerfile.apps
--- a/Dockerfile.apps
+++ b/Dockerfile.apps
@@ -1,4 +1,4 @@
-FROM greenbox:3.0.0
+FROM greenbox:3.0.7
 
 ARG DOCKER_PROXY=172.17.0.4
 
@@ -7,15 +7,6 @@ RUN echo "docker proxy: $DOCKER_PROXY" \
  && echo 'Acquire::HTTPS::Proxy "false";' >> /etc/apt/apt.conf.d/01proxy
 
 RUN apt-get update
-
-ENV LOGROTATE_VER=3.10.0
-RUN apt-get install -y libpopt-dev
-RUN curl -k -LO https://github.com/logrotate/logrotate/releases/download/$LOGROTATE_VER/logrotate-$LOGROTATE_VER.tar.gz &&\
-   tar xvf logrotate-$LOGROTATE_VER.tar.gz &&\
-   cd /logrotate-$LOGROTATE_VER &&\
-   export LDFLAGS="-static" && ./configure --prefix=/opt/apps/green &&\
-   make && make install &&  mkdir -p /opt/apps/green/bin && mv /opt/apps/green/sbin/* /opt/apps/green/bin &&\
-   ls -lh /opt/apps/green/bin/logrotate
 
 
 # https://www.vagrantup.com/downloads.html
@@ -36,11 +27,6 @@ RUN apt-get -y install libssl-dev libncurses5-dev python-dev ruby-dev &&\
      make install &&\
      cd /opt/apps/vim/share/vim && ls -l && mv vim??/* . && rmdir vim??
 
-# ===== neovim ==============
-# RUN  apt-get install -y apt-utils libtool autoconf automake cmake g++ pkg-config unzip &&\
-#     mkdir -p /opt/apps/neovim ; cd /neovim &&\
-#     make || make || make ; cmake -DCMAKE_INSTALL_PREFIX:PATH=/opt/apps/nvim &&\
-#     make all install
 
 # ====== python2 ==============
 # https://pypi.python.org/pypi/pip
@@ -81,6 +67,19 @@ RUN     curl -SL 'https://bootstrap.pypa.io/get-pip.py' | python2 \
 
 # ================= /opt/apps/green =========================================================
 
+
+# == logrotate ==
+ENV LOGROTATE_VER=3.10.0
+RUN apt-get install -y libpopt-dev
+RUN curl -k -LO https://github.com/logrotate/logrotate/releases/download/$LOGROTATE_VER/logrotate-$LOGROTATE_VER.tar.gz &&\
+   tar xvf logrotate-$LOGROTATE_VER.tar.gz &&\
+   cd /logrotate-$LOGROTATE_VER &&\
+   export LDFLAGS="-static" && ./configure --prefix=/opt/apps/green &&\
+   make && make install &&  mkdir -p /opt/apps/green/bin && mv /opt/apps/green/sbin/* /opt/apps/green/bin &&\
+   ls -lh /opt/apps/green/bin/logrotate
+
+
+# === rsync ===
 RUN mkdir -p /opt/apps/green/bin &&\
     cd / && curl -LO https://download.samba.org/pub/rsync/src/rsync-3.1.1.tar.gz &&\
     tar xvf rsync-3.1.1.tar.gz &&\
@@ -91,53 +90,43 @@ RUN curl -LO http://www.ivarch.com/programs/sources/pv-1.6.0.tar.gz  &&\
     tar xvf pv-1.6.0.tar.gz  &&\
     cd /pv-1.6.0 && ./configure && make && /usr/bin/install -c pv /opt/apps/green/bin
 
+# == qperf =====
 RUN cd /tmp && curl -LO https://www.openfabrics.org/downloads/qperf/qperf-0.4.9.tar.gz &&\
     tar xvf qperf-0.4.9.tar.gz &&\
     cd /tmp/qperf-0.4.9 && sh autogen.sh && \
     ./configure && make && /usr/bin/install -c src/qperf /opt/apps/green/bin &&\
     cd /tmp && rm qperf-0.4.9.tar.gz && rm -r -f qperf-0.4.9
 
-RUN curl -LO https://github.com/zfsonlinux/zfs-auto-snapshot/archive/master.zip &&\
-    unzip master.zip &&\
-    cd zfs-auto-snapshot-master && /usr/bin/install src/zfs-auto-snapshot.sh /opt/apps/green/bin/zfs-auto-snapshot
+
+# RUN curl -LO https://github.com/zfsonlinux/zfs-auto-snapshot/archive/master.zip &&\
+#    unzip master.zip &&\
+#    cd zfs-auto-snapshot-master && /usr/bin/install src/zfs-auto-snapshot.sh /opt/apps/green/bin/zfs-auto-snapshot
 
 
-# --------- tmux & libevent install ------------
+# === tmux & libevent install =====
 RUN curl -LO  https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz &&\
     tar xvf libevent-2.0.22-stable.tar.gz &&\
     cd /libevent-2.0.22-stable && sh autogen.sh && ./configure && make install &&\
     ( [  -d /opt/apps/green/lib ] || mkdir -p /opt/apps/green/lib ) &&\
     cp .libs/*so* /opt/apps/green/lib
-
 RUN git clone https://github.com/ThomasAdam/tmux.git tmux &&\
     cd tmux && sh autogen.sh && export LD_LIBRARY_PATH=/opt/apps/green/lib && ./configure && make &&\
     ( [  -d /opt/apps/green/bin ] || mkdir -p /opt/apps/green/bin ) &&\
     cp tmux /opt/apps/green/bin/tmux && chmod +x /opt/apps/green/bin/tmux &&\
     cp /usr/lib/x86_64-linux-gnu/libtinfo.so /opt/apps/green/lib/libtinfo.so.5
 
+# ==== ag - the silver searcher ===========
 RUN  apt-get install -y automake pkg-config libpcre3-dev zlib1g-dev liblzma-dev &&\
      cd / ; git clone https://github.com/ggreer/the_silver_searcher.git &&\
      cd the_silver_searcher && export LDFLAGS="-static" && ./build.sh --prefix=/opt/apps/green &&\
      make install
-
-# --------  green : tcpdump -----------------------------
-ENV TCPDUMP_VER=4.8.1
-ENV LIBPCAP_VER=1.8.1
-RUN apt-get install -y bison flex &&\
-    curl -LO http://www.tcpdump.org/release/libpcap-${LIBPCAP_VER}.tar.gz && tar xvf libpcap-${LIBPCAP_VER}.tar.gz && cd libpcap-${LIBPCAP_VER} &&\
-    ./configure --prefix=/opt/apps/green &&\
-    make install &&\
-    cd / && curl -LO http://www.tcpdump.org/release/tcpdump-${TCPDUMP_VER}.tar.gz && tar xvf tcpdump-${TCPDUMP_VER}.tar.gz &&\
-    cd tcpdump-${TCPDUMP_VER} &&\
-    ./configure --with-crypto=/rootfs/lib/ --prefix=/opt/apps/green --libdir=/opt/apps/green/lib &&\
-    make && make install &&\
-    cd /opt/apps/green && mv sbin/* bin/
 
 # ---------- fio http://jrs-s.net/2015/11/23/fio-cheat-sheet/ ------------
 RUN git clone git://git.kernel.dk/fio.git &&\
     cd fio && ./configure --prefix=/opt/apps/green &&\
     make install
 
+# ==== mbuffer =========
 #Version 20151002 md5=b2d20c4d880518c5fb8f8db734962f45
 # http://www.maier-komor.de/software/mbuffer/mbuffer-20151002.tgz
 RUN export MBUFFER_VER="20151002" && echo "mbuffer ver: $MBUFFER_VER" && curl -LO http://www.maier-komor.de/software/mbuffer/mbuffer-${MBUFFER_VER}.tgz &&\
@@ -174,38 +163,19 @@ RUN     apt-get install -y libusb-1.0-0 libusb-1.0-0-dev libudev1 libudev-dev &&
 	./autogen.sh --prefix=/opt/apps/green &&\
 	make && make install
 
-# ------- docker-compose
+# ===== docker-compose ====
 # https://github.com/docker/compose/releases/
 RUN export DOCKER_COMPOSE_VER=1.8.1 && \
     curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VER}/docker-compose-Linux-x86_64 > /opt/apps/green/bin/docker-compose &&\
     chmod +x /opt/apps/green/bin/docker-compose
 
 
-
 RUN  apt-get update -y &&\
      apt-get -y install gcc libffi-dev libssl-dev python2.7 python2.7-dev  &&\
      ln -s /opt/apps/python2 /opt/python2
 
-# ----- flocker 1.8.0
-#RUN ln -s /opt/apps/python2 /opt/python2 &&\
-#    cd /opt && /opt/python2/bin/virtualenv --python=/opt/python2/bin/python flocker &&\
-#    cd /opt/flocker &&\
-#    . bin/activate && pip install --upgrade pip &&\
-#    cd / &&  git clone https://github.com/ClusterHQ/flocker.git
 
-#RUN cd /opt/flocker &&\
-#    . bin/activate &&\
-#    cd /flocker &&\
-#    pip install --upgrade setuptools &&\
-#    pip install pbr &&\
-#    pip install pycparser &&\
-#    pip install twisted --verbose &&\
-#    pip install . &&\
-#    cp /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /opt/flocker/lib/ &&\
-#    cp /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /opt/flocker/lib/
-
-
-# --- pipework in green
+# ==== pipework in green ====
 RUN  cd /opt/apps/green/bin &&  curl -LO https://raw.githubusercontent.com/jpetazzo/pipework/master/pipework &&\
      chmod +x pipework
 
@@ -213,7 +183,6 @@ RUN  apt-get update -y && apt-get install -y bridge-utils openvswitch-switch &&\
      cp /sbin/brctl /opt/apps/green/bin/ &&\
      cp `which ovs-vsctl` /opt/apps/green/bin/ &&\
      cp `which truncate` /opt/apps/green/bin/
-
 
 
 # --- aws cli
@@ -292,7 +261,6 @@ RUN echo "X11 `ls -ld /usr/share/X11/*`"  && mkdir -p /opt/apps/x11/share ; cp -
    rm -rf /opt/apps/x11/lib/libdrm_*  # exclude drm drivers
 
 
-
 # ==== ruby ============================================================================
 # https://github.com/docker-library/ruby/blob/master/2.3/Dockerfile
 # skip installing gem documentation
@@ -368,110 +336,84 @@ RUN mkdir -p "$GEM_HOME" "$BUNDLE_BIN" \
 	&& chmod 777 "$GEM_HOME" "$BUNDLE_BIN"
 
 
-RUN curl -LO ftp://sources.redhat.com/pub/lvm2/releases/LVM2.2.02.164.tgz &&\
-    tar xf LVM2*.tgz &&\
-    cd LVM2* &&\
-    ./configure --prefix=/opt/apps/green &&\
-    make install
+ENV TCL_REPO_BASE=http://tinycorelinux.net/7.x/x86_64
+ENV TCZ_DEPS_DEV    curl-dev \
+                    openssl-dev \
+                    ncurses-dev \
+                    ncurses \
+                    expat2-dev \
+                    readline-dev \
+                    libxml2-dev
 
-RUN curl -LO http://ftp.gnu.org/gnu/parted/parted-3.2.tar.xz
-RUN tar xf parted-3.2.tar.xz &&\
-    cd parted-3* &&\
-    apt-get install libreadline-dev -y &&\
-    LDFLAGS='-L/opt/apps/green/lib/' && export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' && ./configure --prefix=/opt/apps/green  &&\
-    make install
-
-
-# http://www.linuxfromscratch.org/blfs/view/svn/basicnet/bind-utils.html
-RUN curl -LO ftp://ftp.isc.org/isc/bind9/9.11.0/bind-9.11.0.tar.gz &&\
-    tar xf bind-*.tar.gz && cd bind-* &&\
-    export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' && ./configure --prefix=/opt/apps/green &&\
-    ./configure --prefix=/opt/apps/green && make -C lib/dns && make -C lib/isc && make -C lib/bind9 && make -C lib/isccfg && make -C lib/lwres &&\
-     make -C bin/dig install
-
-
-#RUN curl -LO https://curl.haxx.se/download/curl-7.51.0.tar.bz2 &&\
-#    tar xf curl*.tar.bz2 &&\
-#    cd curl*7.51.0 &&\
-#    export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-#    ./configure --prefix=/opt/apps/green &&\
-#    make install
+ENV ROOTFS=/
+# Install the base tiny linux build
+RUN for dep in $TCZ_DEPS_DEV ; do \
+        echo "Download $TCL_REPO_BASE/tcz/$dep.tcz"  && \
+        curl -L -o /tmp/$dep.tcz $TCL_REPO_BASE/tcz/$dep.tcz && \
+        if [ ! -s /tmp/$dep.tcz ] ; then \
+            echo "$TCL_REPO_BASE/tcz/$dep.tcz size is zero 0 - error !" && \
+            exit 1 ;\
+        else \
+            unsquashfs -i -f -d $ROOTFS /tmp/$dep.tcz && \
+            rm -f /tmp/$dep.tcz ;\
+            if [ "$?" != "0" ] ; then exit 1 ; fi ;\
+        fi ;\
+done
 
 
-ENV GIT_VER=2.10.2
-# http://www.linuxfromscratch.org/blfs/view/svn/general/git.html
-RUN curl -LO ftp://ftp.kernel.org/pub/software/scm/git/git-${GIT_VER}.tar.xz
-RUN tar xf git-${GIT_VER}.tar.xz && cd git-${GIT_VER} &&\
-    apt-get install gettext  libcurl4-openssl-dev -y &&\
-# mismatch between tinycore and debian libraries - force build with tiny core libs
-    cp $ROOTFS/usr/local/lib/libcrypto.so* /usr/lib/x86_64-linux-gnu/ &&\
-    cp $ROOTFS/usr/local/lib/libcurl.* /usr/lib/x86_64-linux-gnu/ &&\
-    export LDFLAGS='-static' && CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-# erase git-imap-send .... IMAP_SEND_LDFLAGS) multiline, git-imap-send cannot be compiled static
-    perl  -i.origin -pe 'BEGIN{undef $/;} s/^gitt-imap-send.*filter.*IMAP_SEND_LDFLAGS\)$//smg' Makefile &&\
-    perl  -i.origin -pe 's/^PROGRAM_OBJS.*imap-send.o$//smg' Makefile &&\
-    ./configure --with-curl --with-expat --with-tcltk=no \
-       --with-pager=more \
-       --with-editor=vim \
-       --prefix=/opt/apps/green &&\
-    make install
+ENV ROOTFS=/opt/apps/green
+ENV TCL_REPO_BASE=http://tinycorelinux.net/7.x/x86_64
+ENV TCZ_DEPS_GREEN  \
+                    nfs-utils tcp_wrappers portmap rpcbind libtirpc \
+                    htop ncurses-utils ncurses-terminfo \
+                    git expat2 \
+                    patch pcre \
+                    parted liblvm2 \
+                    strace glib2 libtirpc \
+                    procps \
+                    nfs-utils tcp_wrappers portmap rpcbind libtirpc \
+                    bind-utilities libxml2 \
+                    libpcap tcpdump \
+                    cifs-utils \
+                    fuse libffi
 
-# ncurses 6.0 utf support
-#RUN curl -LO ftp://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz &&\
-#    tar xf ncurses*.tar.gz &&\
-#    cd ncurses-6.0 &&\
-#    export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-#    ./configure --enable-widec --prefix=/opt/apps/green &&\
-#    make && make install &&\
-#    ls /opt/apps/green/bin/ncursesw6-config
 
-RUN git clone https://github.com/hishamhm/htop &&\
-    cd htop &&\
-    export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-    ./autogen.sh && ./configure --with-sysroot=/rootfs --enable-cgroup --prefix=/opt/apps/green  &&\
-    make install
+# Install the base tiny linux build
+RUN for dep in $TCZ_DEPS_GREEN ; do \
+        echo "Download $TCL_REPO_BASE/tcz/$dep.tcz"  && \
+        curl -L -o /tmp/$dep.tcz $TCL_REPO_BASE/tcz/$dep.tcz && \
+        if [ ! -s /tmp/$dep.tcz ] ; then \
+            echo "$TCL_REPO_BASE/tcz/$dep.tcz size is zero 0 - error !" && \
+            exit 1 ;\
+        else \
+            unsquashfs -i -f -d $ROOTFS /tmp/$dep.tcz && \
+            rm -f /tmp/$dep.tcz ;\
+            if [ "$?" != "0" ] ; then exit 1 ; fi ;\
+        fi ;\
+done
+
+RUN mkdir -p /opt/apps/{bin,share,lib} &&\
+    cp -av /opt/apps/green/usr/local/bin/* /opt/apps/green/bin/ &&\
+    cp -av /opt/apps/green/usr/local/sbin/* /opt/apps/green/bin/ &&\
+    cp -av /opt/apps/green/usr/local/lib/* /opt/apps/green/lib/ &&\
+    cp -av /opt/apps/green/usr/local/share/* /opt/apps/green/share/ &&\
+    rm -rf /opt/apps/green/usr
+
+
 
 RUN rm -rf /opt/apps/green/bin/git-cvsserver &&\
-    rm -rf /opt/apps/green/libexec/git-core/git-cvs* &&\
-    rm -rf /opt/apps/green/libexec/git-core/git-svn* &&\
-    rm -rf /opt/apps/green/libexec/git-core/git-web--browse*
+    rm -rf /opt/apps/green/lib/git-core/git-cvs* &&\
+    rm -rf /opt/apps/green/lib/git-core/git-svn* &&\
+    rm -rf /opt/apps/green/lib/git-core/git-web--browse*
 
+# erase tcpdump.4.8.1
+RUN rm -rf /opt/apps/green/bin/tcpdump.*
 
-#RUN echo "deb-src http://deb.debian.org/debian jessie main" >> /etc/apt/sources.list &&\
-#   apt-get update &&\
-#   apt-get build-dep samba -y && curl -LO https://download.samba.org/pub/samba/stable/samba-4.3.12.tar.gz
-#RUN tar xf samba-4*.gz && cd samba-4* && ./configure --prefix=/opt/apps/green &&\
-#    make && make install
-
-
-#RUN curl -LO http://downloads.sourceforge.net/project/libtirpc/libtirpc/1.0.1/libtirpc-1.0.1.tar.bz2
-#RUN  export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-#    tar xf libti*bz2 && cd libtirpc*1.0.1 &&\
-#    ./configure --prefix=/opt/apps/green &&\
-#    make install
-
-#RUN curl -LO http://sqlite.org/2016/sqlite-autoconf-3150000.tar.gz
-#RUN export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-#    tar xf sqlite*.tar.gz && cd sqlite*0 &&\
-#    ./configure --prefix=/opt/apps/green &&\
-#    make install
-
-#RUN curl -LO https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.25.tar.xz
-#RUN export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-#    tar xf libcap*.tar.xz && cd libcap-2.25 &&\
-#    make install DESTDIR=/opt/apps/green &&\
-#    make install
-
-#RUN curl -LO http://downloads.sourceforge.net/nfs/nfs-utils-1.3.4.tar.bz2
-#RUN apt-get install libwrap0 -y &&\
-#    export CFLAGS='-I/opt/apps/green/include -L/opt/apps/green/lib' &&\
-#    tar xf nfs-utils*.bz2 && cd nfs-utils*1.3.4 &&\
-#    ./configure --prefix=/opt/apps/green &&\
-#    make install
-
+# erase static libraries, includes in /opt/apps/green
 RUN rm /opt/apps/green/lib/*.a &&\
     rm /opt/apps/green/lib/*.la && echo green_apps removing static libraries
 RUN rm -rf /opt/apps/green/include/ ; echo green_apps removing include files
+
 RUN rm -rf /opt/apps/green/share /opt/apps/green/opt
 RUN mv /opt/apps/green/sbin/* /opt/apps/green/bin/ ; rmdir /opt/apps/green/sbin
 RUN echo "/opt/apps/green:" && ls -l /opt/apps/green
@@ -482,5 +424,5 @@ COPY extract_so_deps_x11.sh /
 RUN bash  /extract_so_deps_x11.sh
 
 # collect shared libraries needed for green apps execution
-COPY extract_so_deps_green.sh /
-RUN bash  /extract_so_deps_green.sh
+#COPY extract_so_deps_green.sh /
+#RUN bash  /extract_so_deps_green.sh
