booted

diff --git a/rootfs/rootfs/etc/rc.d/scaleway b/rootfs/rootfs/etc/rc.d/scaleway
--- a/rootfs/rootfs/etc/rc.d/scaleway
+++ b/rootfs/rootfs/etc/rc.d/scaleway
@@ -9,5 +9,10 @@ then
 fi
 
 # https://community.online.net/t/openbsd-on-a-vc1/1933
-echo "SCALEWAY Signalink server state: booted"
-curl http://$SCALEWAY_SIGNAL_SERVER/state -X PATCH -H 'Content-Type: application/json' -d '{"state_detail": "booted"}' &
+
+if ! curl http://$SCALEWAY_SIGNAL_SERVER/state -X PATCH -H 'Content-Type: application/json' -d '{"state_detail": "booted"}'
+then
+  echo "${RED}SCALEWAY Signalink server $SCALEWAY_SIGNAL_SERVER ERROR${NORMAL}"
+else
+  echo "${GREEN}SCALEWAY Signalink server booted OK${NORMAL}"
+fi
