cgroupfs-mount problemi

diff --git a/rootfs/cgroupfs-mount b/rootfs/cgroupfs-mount
--- a/rootfs/cgroupfs-mount
+++ b/rootfs/cgroupfs-mount
@@ -22,29 +22,29 @@ mountpoint() {
 # if cgroup is mounted by fstab, don't run
 # don't get too smart - bail on any uncommented entry with 'cgroup' in it
 if grep -v '^#' /etc/fstab | grep -q cgroup; then
-	log_msg 'cgroups mounted from fstab, not mounting /sys/fs/cgroup'
-	exit 0
+	log_msg 'cgroups mounted from fstab, not mounting /sys/fs/cgroup' R
+	exit 1
 fi
 
-# kernel provides cgroups?
+
 if [ ! -e /proc/cgroups ]; then
-	exit 0
+	log_msg "kernel doesn't provides cgroups!?, not mounting /sys/fs/cgroup" R
+	exit 1
 fi
 
-# if we don't even have the directory we need, something else must be wrong
 if [ ! -d /sys/fs/cgroup ]; then
-	exit 0
+	log_msg "No directory /sys/fs/cgroup ERROR" R
+	exit 1
 fi
 
 # mount /sys/fs/cgroup if not already done
 if ! mountpoint -q /sys/fs/cgroup; then
 	    /bin/mount -t tmpfs -o uid=0,gid=0,mode=0755 cgroup /sys/fs/cgroup
-			log_msg  "mounting /sys/fs/cgroup ($?)" G
+			log_msg  "mounting /sys/fs/cgroup on tmpfs ($?)" G
 fi
 
 cd /sys/fs/cgroup
-
-for sys in $(awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
+for sys in $(/usr/bin/awk '!/^#/ { if ($4 == 1) print $1 }' /proc/cgroups); do
 	mkdir -p $sys
 	if ! mountpoint -q $sys; then
 		  if ! /bin/mount -n -t cgroup -o $sys cgroup $sys; then
